# use this to spin up elasticsearch containers with secure connections
version: '3.6'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    restart: always
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - net
    depends_on:
      - elasticsearch

volumes:
  elastic_data:
  kibana_data:

networks:
  net:
