name: Format Java code as per Google-Java-Format program

on: [ push, pull_request ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          skip-commit: true
      - name: Print diffs
        run: |
          echo "If build failed, please read the README.md file,install pre-commit hooks to properly format the files and push your changes"
          git --no-pager diff --exit-code
