# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trigger-tests-on-external-event

on:
  repository_dispatch:
    types: [deployment-completed-notification-event]

jobs:
  trigger-tests-on-external-event:
    uses: ./.github/workflows/run-tests-template.yml
    with:
      tags-of-tests-to-include: ${{ github.event.client_payload.TAG }}
      tags-of-tests-to-exclude: "" #-DexcludedGroups="" means exclude none of groups/tests
      test-environment: ${{github.event.client_payload.TEST_ENV}}
    secrets: inherit
